# Generated by Django 3.1.1 on 2020-09-15 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('genre', models.PositiveSmallIntegerField(choices=[(0, 'Wojenny'), (1, 'Dramat obyczajowy'), (2, 'Przygodowy'), (3, 'Thriller'), (4, 'Horror'), (5, 'Historyczny'), (6, 'Komedia miłosna'), (7, 'Melodramat'), (8, 'Komedia')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, default=2000)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(default='', max_length=200)),
                ('imdb_link', models.URLField(null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('premiere', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('extra_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField(default='Brak recenzji.')),
                ('stars', models.PositiveSmallIntegerField(default=3)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('movies', models.ManyToManyField(to='main.Movie')),
            ],
        ),
    ]
